title: Loading...
author: Zhenye Na
email: zna2@illinois.edu
description: > # this means to ignore newlines until "twitter_username:"
  Graduate student @ UIUC<br>Google-Oriented-Programming

# baseurl: "/home/"
# url: "https://zhenye-na.github.io"

# social links
# twitter_username: jekyllrb
github_username:  Zhenye-Na
# rss: rss
# dribbble_username: jekyll
facebook_username: zhenye.na.1
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: zhenyena
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com
header_pages:
  - portfolio.md
  - tags.md
  - about.md

github:
  repo: https://github.com/Zhenye-Na/Zhenye-Na.github.io/


disqus:
  shortname: zhenye
# defaults:
#   -
#     scope:
#       path: ""
#       type: "posts"
#     values:
#       comments: true

show_excerpts: false # set to true to show excerpts on the homepage

google_analytics: UA-116457928-1

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
